# This docker-compose configuration is only to be run in a development context.
# When its closer to the submission date, a production ready version will be created.
version: '3.6'
services:
  api: # Hosts the API portion of the system.
    depends_on:
      - migrator
    build: ./api/
    ports:
      - 8080:8088
    volumes:
      - ./api:/home/api/code
      - ./db:/home/api/db
      - ./config:/home/api/config
    environment:
      - SCENARIO=development
      - DOCKER=1
    command: npm run dockerStart
#  gui: # Hosts the GUI portion of the system.
#    depends_on:
#      - api
#    build: ./gui/
#    ports:
#      - 80:3000
#    volumes:
#      - ./gui:/home/gui/code
#      - ./config:/home/gui/config
#    environment:
#      - SCENARIO=development
#      - DOCKER=1
#    command: npm run dockerDev
  img: # Hosts the image server portion of the system.
    depends_on:
      - migrator
    build: ./img/
    ports:
      - 8888:8888
    volumes:
      - ./img:/home/img/code
      - ./db:/home/img/db
      - ./config:/home/img/config
    environment:
      - SCENARIO=development
      - DOCKER=1
    command: npm run dockerStart
  db: # Hosts the database. This currently will not persist database contents.
    image: mysql:5.7.21
    environment:
      MYSQL_DATABASE: "carsharedb"
      MYSQL_ROOT_PASSWORD: dev_root # Username is just 'root'
  adminer: # This is a tool for interacting with the database, and it not essential for systems functionality.
    depends_on:
      - db
    image: adminer:4.6.2-standalone
    ports:
      - 5050:8080
  migrator: # Handles database migration process.
    depends_on:
      - db
    build: ./db/
    volumes:
      - ./db:/home/migrator/code
      - ./config:/home/migrator/config
    environment:
      - SCENARIO=development
      - DOCKER=1
    command: npm run dockerMigrate
  mail: # Catches sent emails
    image: schickling/mailcatcher
    ports:
      - 1080:1080
# For later: Production deployment should handle install operations, not each container. Automatic install here is for convenience.
    